#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : not-ffmpeg
Version  : 4.1.1.reduced
Release  : 24
URL      : http://localhost/cgit/projects/ffmpeg/snapshot/ffmpeg-4.1.1-reduced.tar.xz
Source0  : http://localhost/cgit/projects/ffmpeg/snapshot/ffmpeg-4.1.1-reduced.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1 LGPL-3.0
Requires: not-ffmpeg-bin = %{version}-%{release}
Requires: not-ffmpeg-data = %{version}-%{release}
Requires: not-ffmpeg-lib = %{version}-%{release}
Requires: not-ffmpeg-license = %{version}-%{release}
BuildRequires : gmp-dev
BuildRequires : libass-dev
BuildRequires : pkgconfig(libmfx)
BuildRequires : pkgconfig(libv4l2)
BuildRequires : pkgconfig(libva)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(sdl2)
BuildRequires : pkgconfig(vorbis)
BuildRequires : pkgconfig(vpx)
BuildRequires : rtmpdump-dev
Patch1: 0001-configure-do-not-die-if-unknown-option-is-found.patch
Patch2: 0001-not-ffmpeg-fixes-to-compilation-for-this-version.patch
Patch3: CVE-2019-12730.patch
Patch4: CVE-2019-11339.patch

%description
BFIN optimizations have been removed in
commit 880e2aa23645ed9871c66ee1cbd00f93c72d2d73
The last revission with the optimizations is fa4e17c14035ebf43130fb369e1728cdd98d0b72

%package bin
Summary: bin components for the not-ffmpeg package.
Group: Binaries
Requires: not-ffmpeg-data = %{version}-%{release}
Requires: not-ffmpeg-license = %{version}-%{release}

%description bin
bin components for the not-ffmpeg package.


%package data
Summary: data components for the not-ffmpeg package.
Group: Data

%description data
data components for the not-ffmpeg package.


%package dev
Summary: dev components for the not-ffmpeg package.
Group: Development
Requires: not-ffmpeg-lib = %{version}-%{release}
Requires: not-ffmpeg-bin = %{version}-%{release}
Requires: not-ffmpeg-data = %{version}-%{release}
Provides: not-ffmpeg-devel = %{version}-%{release}
Requires: not-ffmpeg = %{version}-%{release}

%description dev
dev components for the not-ffmpeg package.


%package lib
Summary: lib components for the not-ffmpeg package.
Group: Libraries
Requires: not-ffmpeg-data = %{version}-%{release}
Requires: not-ffmpeg-license = %{version}-%{release}

%description lib
lib components for the not-ffmpeg package.


%package license
Summary: license components for the not-ffmpeg package.
Group: Default

%description license
license components for the not-ffmpeg package.


%prep
%setup -q -n ffmpeg-4.1.1-reduced
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1565903782
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static --extra-ldflags='-ldl' \
--disable-everything \
--enable-avcodec \
--enable-avformat \
--enable-avutil \
--enable-avdevice \
--enable-rdft \
--enable-pixelutils \
--enable-libvorbis \
--enable-libvpx \
--enable-muxer="crc,image2,jpeg,ogg,md5,nut,webm,webm_chunk,webm_dash_manifest,rawvideo,ivf,null,wav,framecrc,rtp,rtsp,ass,webvtt" \
--enable-bsf="mp3_header_decompress,vp9_superframe" \
--enable-demuxer="mjpeg,image2,webm_dash_manifest,ogg,matroska,mp3,pcm_s16le,rawvideo,wav,mov,ivf,rtp,rtsp,flv,ass,subviewer,subviewer1,webvtt" \
--enable-decoder="rawvideo,libvorbis,mjpeg,jpeg,opus,mp3,pcm_u8,pcm_s16le,pcm_s24le,pcm_s32le,pcm_f32le,pcm_s16be,pcm_s24be,pcm_mulaw,pcm_alaw,pcm_u24le,pcm_u32be,pcm_u32le,pgm,pgmyuv,libvpx_vp8,vp8_qsv,vp8,libvpx_vp9,vp9,tiff,bmp,wavpack,ass,saa,subviewer,subviewer1,webvtt" \
--enable-encoder="rawvideo,wrapped_avframe,libvorbis,opus,yuv4,tiff,bmp,libvpx_vp8,vp8_vaapi,libvpx_vp9,vp9_vaapi,mjpeg_vaapi,pcm_u8,pcm_s16le,pcm_s24le,pcm_s32le,pcm_f32le,pcm_s16be,pcm_s24be,pcm_mulaw,pcm_alaw,pcm_u24le,pcm_u32be,pcm_u32le,ass,ssa,webvtt" \
--enable-hwaccel="vp8_vaapi,vp9_vaapi,mjpeg_vaapi" \
--enable-parser="opus,libvorbis,vp3,vp8,vp9" \
--enable-protocol="file,md5,pipe,rtp,tcp,http,https,httpproxy,ftp,librtmp,librtmpe,librtmps,librtmpt,librtmpte,rtmpe,rtmps,rtmpt,rtmpte,rtmpts" \
--enable-filter="aresample,asetpts,denoise_vaapi,deinterlace_vaapi,hwupload,hwdownload,pixdesctest,procamp_vaapi,scale,scale_vaapi,sharpness_vaapi,color,format,subtitles" \
--disable-error-resilience \
--enable-pic \
--enable-shared \
--enable-swscale \
--enable-avfilter \
--enable-vaapi \
--enable-libmfx \
--disable-xvmc \
--disable-doc \
--disable-htmlpages \
--enable-version3 \
--disable-mmx \
--disable-mmxext \
--disable-programs \
--enable-ffmpeg \
--enable-ffplay \
--enable-sdl2 \
--enable-network \
--enable-openssl \
--enable-librtmp \
--enable-libv4l2 \
--enable-indev=v4l2 \
--enable-libass
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1565903782
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/not-ffmpeg
cp COPYING.LGPLv2.1 %{buildroot}/usr/share/package-licenses/not-ffmpeg/COPYING.LGPLv2.1
cp COPYING.LGPLv3 %{buildroot}/usr/share/package-licenses/not-ffmpeg/COPYING.LGPLv3
cp LICENSE.md %{buildroot}/usr/share/package-licenses/not-ffmpeg/LICENSE.md
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ffmpeg
/usr/bin/ffplay

%files data
%defattr(-,root,root,-)
/usr/share/examples/Makefile
/usr/share/examples/README
/usr/share/examples/avio_dir_cmd.c
/usr/share/examples/avio_reading.c
/usr/share/examples/decode_audio.c
/usr/share/examples/decode_video.c
/usr/share/examples/demuxing_decoding.c
/usr/share/examples/encode_audio.c
/usr/share/examples/encode_video.c
/usr/share/examples/extract_mvs.c
/usr/share/examples/filter_audio.c
/usr/share/examples/filtering_audio.c
/usr/share/examples/filtering_video.c
/usr/share/examples/http_multiclient.c
/usr/share/examples/hw_decode.c
/usr/share/examples/metadata.c
/usr/share/examples/muxing.c
/usr/share/examples/qsvdec.c
/usr/share/examples/remuxing.c
/usr/share/examples/resampling_audio.c
/usr/share/examples/scaling_video.c
/usr/share/examples/transcode_aac.c
/usr/share/examples/transcoding.c
/usr/share/examples/vaapi_encode.c
/usr/share/examples/vaapi_transcode.c
/usr/share/ffprobe.xsd
/usr/share/libvpx-1080p.ffpreset
/usr/share/libvpx-1080p50_60.ffpreset
/usr/share/libvpx-360p.ffpreset
/usr/share/libvpx-720p.ffpreset
/usr/share/libvpx-720p50_60.ffpreset

%files dev
%defattr(-,root,root,-)
/usr/include/libavcodec/ac3_parser.h
/usr/include/libavcodec/adts_parser.h
/usr/include/libavcodec/avcodec.h
/usr/include/libavcodec/avdct.h
/usr/include/libavcodec/avfft.h
/usr/include/libavcodec/d3d11va.h
/usr/include/libavcodec/dirac.h
/usr/include/libavcodec/dv_profile.h
/usr/include/libavcodec/dxva2.h
/usr/include/libavcodec/jni.h
/usr/include/libavcodec/mediacodec.h
/usr/include/libavcodec/qsv.h
/usr/include/libavcodec/vaapi.h
/usr/include/libavcodec/vdpau.h
/usr/include/libavcodec/version.h
/usr/include/libavcodec/videotoolbox.h
/usr/include/libavcodec/vorbis_parser.h
/usr/include/libavcodec/xvmc.h
/usr/include/libavdevice/avdevice.h
/usr/include/libavdevice/version.h
/usr/include/libavfilter/avfilter.h
/usr/include/libavfilter/buffersink.h
/usr/include/libavfilter/buffersrc.h
/usr/include/libavfilter/version.h
/usr/include/libavformat/avformat.h
/usr/include/libavformat/avio.h
/usr/include/libavformat/version.h
/usr/include/libavutil/adler32.h
/usr/include/libavutil/aes.h
/usr/include/libavutil/aes_ctr.h
/usr/include/libavutil/attributes.h
/usr/include/libavutil/audio_fifo.h
/usr/include/libavutil/avassert.h
/usr/include/libavutil/avconfig.h
/usr/include/libavutil/avstring.h
/usr/include/libavutil/avutil.h
/usr/include/libavutil/base64.h
/usr/include/libavutil/blowfish.h
/usr/include/libavutil/bprint.h
/usr/include/libavutil/bswap.h
/usr/include/libavutil/buffer.h
/usr/include/libavutil/camellia.h
/usr/include/libavutil/cast5.h
/usr/include/libavutil/channel_layout.h
/usr/include/libavutil/common.h
/usr/include/libavutil/cpu.h
/usr/include/libavutil/crc.h
/usr/include/libavutil/des.h
/usr/include/libavutil/dict.h
/usr/include/libavutil/display.h
/usr/include/libavutil/downmix_info.h
/usr/include/libavutil/encryption_info.h
/usr/include/libavutil/error.h
/usr/include/libavutil/eval.h
/usr/include/libavutil/ffversion.h
/usr/include/libavutil/fifo.h
/usr/include/libavutil/file.h
/usr/include/libavutil/frame.h
/usr/include/libavutil/hash.h
/usr/include/libavutil/hmac.h
/usr/include/libavutil/hwcontext.h
/usr/include/libavutil/hwcontext_cuda.h
/usr/include/libavutil/hwcontext_d3d11va.h
/usr/include/libavutil/hwcontext_drm.h
/usr/include/libavutil/hwcontext_dxva2.h
/usr/include/libavutil/hwcontext_mediacodec.h
/usr/include/libavutil/hwcontext_qsv.h
/usr/include/libavutil/hwcontext_vaapi.h
/usr/include/libavutil/hwcontext_vdpau.h
/usr/include/libavutil/hwcontext_videotoolbox.h
/usr/include/libavutil/imgutils.h
/usr/include/libavutil/intfloat.h
/usr/include/libavutil/intreadwrite.h
/usr/include/libavutil/lfg.h
/usr/include/libavutil/log.h
/usr/include/libavutil/lzo.h
/usr/include/libavutil/macros.h
/usr/include/libavutil/mastering_display_metadata.h
/usr/include/libavutil/mathematics.h
/usr/include/libavutil/md5.h
/usr/include/libavutil/mem.h
/usr/include/libavutil/motion_vector.h
/usr/include/libavutil/murmur3.h
/usr/include/libavutil/opt.h
/usr/include/libavutil/parseutils.h
/usr/include/libavutil/pixdesc.h
/usr/include/libavutil/pixelutils.h
/usr/include/libavutil/pixfmt.h
/usr/include/libavutil/random_seed.h
/usr/include/libavutil/rational.h
/usr/include/libavutil/rc4.h
/usr/include/libavutil/replaygain.h
/usr/include/libavutil/ripemd.h
/usr/include/libavutil/samplefmt.h
/usr/include/libavutil/sha.h
/usr/include/libavutil/sha512.h
/usr/include/libavutil/spherical.h
/usr/include/libavutil/stereo3d.h
/usr/include/libavutil/tea.h
/usr/include/libavutil/threadmessage.h
/usr/include/libavutil/time.h
/usr/include/libavutil/timecode.h
/usr/include/libavutil/timestamp.h
/usr/include/libavutil/tree.h
/usr/include/libavutil/twofish.h
/usr/include/libavutil/version.h
/usr/include/libavutil/xtea.h
/usr/include/libswresample/swresample.h
/usr/include/libswresample/version.h
/usr/include/libswscale/swscale.h
/usr/include/libswscale/version.h
/usr/lib64/libavcodec.so
/usr/lib64/libavdevice.so
/usr/lib64/libavfilter.so
/usr/lib64/libavformat.so
/usr/lib64/libavutil.so
/usr/lib64/libswresample.so
/usr/lib64/libswscale.so
/usr/lib64/pkgconfig/libavcodec.pc
/usr/lib64/pkgconfig/libavdevice.pc
/usr/lib64/pkgconfig/libavfilter.pc
/usr/lib64/pkgconfig/libavformat.pc
/usr/lib64/pkgconfig/libavutil.pc
/usr/lib64/pkgconfig/libswresample.pc
/usr/lib64/pkgconfig/libswscale.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libavcodec.so.58
/usr/lib64/libavcodec.so.58.35.100
/usr/lib64/libavdevice.so.58
/usr/lib64/libavdevice.so.58.5.100
/usr/lib64/libavfilter.so.7
/usr/lib64/libavfilter.so.7.40.101
/usr/lib64/libavformat.so.58
/usr/lib64/libavformat.so.58.20.100
/usr/lib64/libavutil.so.56
/usr/lib64/libavutil.so.56.22.100
/usr/lib64/libswresample.so.3
/usr/lib64/libswresample.so.3.3.100
/usr/lib64/libswscale.so.5
/usr/lib64/libswscale.so.5.3.100

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/not-ffmpeg/COPYING.LGPLv2.1
/usr/share/package-licenses/not-ffmpeg/COPYING.LGPLv3
/usr/share/package-licenses/not-ffmpeg/LICENSE.md
